"""Ajout de nouveaux champs

Revision ID: 73863faa6df9
Revises: a3b42773b872
Create Date: 2024-10-12 18:12:53.993958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73863faa6df9'
down_revision = 'a3b42773b872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
